# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dhammadha.ro
email: buddhasasana.ro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sutre buddhiste Theravāda și învățățuri din Tradiția Pădurii Thailandeze.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://dhammadha.ro # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - semantic
  - node_modules
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections_dir: tipitaka
collections:
  kn_dhp:
    order:
      - 00-copyright.md
      - 00-introducere-prefata.md
      - 00-prefata-traducatorului.md
    output: true
    permalink: /tipitaka/kn/dhammapada/:name
  mn:
    output: true
    permalink: /tipitaka/mn/:name
  sn:
    output: true
    permalink: /tipitaka/sn/:name
  kn_ud:
    output: true
    permalink: /tipitaka/kn/ud/:name
  teka:
    output: false
